### PR TITLE
Fixed #1

### LINKED ISSUE #1: Configure language of downloaded Iso
Hey, i would like to give this a try with your other project https://github.com/ianis58/tiny11builder but i would like to be able to change the language of the downloaded iso. Default seems to be english. I have seen there is a config.json file with "language:English". I have tried changing that language, but then the programm crashes.

Would be great to have a simple cli option to change the language

### PR DESCRIPTION
**Pull request by Joly0**
Edit:
implements the option to specify the language by running ".\WindowsIsoDownloader.exe German" for german iso or ".\WindowsIsoDownloader.exe French" for french language. All other languages are supported as of the selection menu on the download page here https://www.microsoft.com/en-us/software-download/windows11/

### CODE REVIEW

**Comment by ianis58** [comment]
Seems like you use the label of a select option, but you need to use the value.
You can use your browser to inspect the page and see the select, it's options, and the labels and values of each option.

**Comment by ianis58** [comment]
Also I prefer not to handle different languages because for tiny11builder it makes things easier.
After installing windows 11, you can always go in the settings, and change the language (it will automatically download the required language files).
After signing out and back in your user account, the new display language will be applied. :)

**Comment by Joly0** [comment]
> Seems like you use the label of a select option, but you need to use the value. You can use your browser to inspect the page and see the select, it's options, and the labels and values of each option.

I dont quite understand what you mean? Why do i have to use the value? It is working like that, i have tested it with multiple languages and all of them work.

**Comment by Joly0** [comment]
> Also I prefer not to handle different languages because for tiny11builder it makes things easier. After installing windows 11, you can always go in the settings, and change the language (it will automatically download the required language files). After signing out and back in your user account, the new display language will be applied. :)

It wont change anything for tiny11builder, but it just adds the functionality if wanted. By default (not specyfing any langauge like .\WindowsIsoDownloader.exe German"), it will still download the default English iso.

And i know, i can change the language later, but why download and maybe slim down an iso, if you are going to add languages later anyway? Thats imo just unneeded bloat, just download the correct iso straight away and thats it

**Comment by Joly0** [comment]
So, will this get merged?

**Comment by Joly0** [comment]
@ianis58 Will this get merged?

**Comment by Joly0** [comment]
Btw, the download doesnt work anymore, so i fixed it. Can this please get merged?

**Comment by ianis58** [comment]
I prefer not to merge the language parameter support, it's an interesting feature but language can be selected once the OS is installed.
Thanks for noticing the error for the iso download, i'll make a fix because we need to use the value and not the option's display text.

**Pull request closed without merging**
